alter table bank_contact drop foreign key FKaxnpdk31fp707ousdyu5ilra6;
alter table bank_contact2 drop foreign key FKhkjbbk5fen965yadvjse4giau;
alter table budget_transaction drop foreign key FKemsmc6k4c5ueumaoxac69nto3;
alter table budget_transaction drop foreign key FKd29kggwou1k21wratamdv7kky;
alter table credential drop foreign key FKlde6756f90cgp6ssa39p6jh3b;
alter table transaction drop foreign key FK6g20fcr3bhr6bihgy24rq1r1b;
alter table user_address drop foreign key FKn5cqa3r4dp2k5l945c3w8iqn7;
drop table if exists account;
drop table if exists bank;
drop table if exists bank_contact;
drop table if exists bank_contact2;
drop table if exists budget;
drop table if exists budget_transaction;
drop table if exists credential;
drop table if exists finances_user;
drop table if exists hibernate_sequence;
drop table if exists ifinaces_keys;
drop table if exists transaction;
drop table if exists user_address;
